apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-48db
  namespace: e2e-demos-bsen-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:1c411035288d7e5903924f70c093f277680b27418bb6e89da5c34e741d83801c
        name: main
        resources: {}
status: {}
